<?php

namespace AIProject\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Exercise_scoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exercise_scoreRepository extends EntityRepository
{
}
